import { CertificationType } from "@/@types";
import { GITHUB_URL } from ".";

export const CERIFICATIONS: CertificationType[] = [
  {
    id: "1",
    title: "Data Structures and Algorithms",
    description: "Earned ELITE + SILVER for scoring 78% in Data Structures and Algorithms using Python from NPTEL",
    certificate: "https://www.hackerrank.com/certificates/9b1b1f9e1b5d",
    date: "09 Sept, 2022",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "second_rank.png",
  },
  {
    id: "2",
    title: "Problem Solving (Basic)",
    description: "I completed my Basics of web course from Codedamn.",
    date: "15th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "basics_of_web.png",
  },
  {
    id: "3",
    title: "Problem Solving (Intermediate)",
    description: "I completed my Basics of Js course from Codedamn.",
    date: "15th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "basic_js.png",
  },
  {
    id: "4",
    title: "Python",
    description: "I completed my Basics of html,css course from Codedamn.",
    date: "15th Aug, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "html_css.png",
  },
  {
    id: "5",
    title: "Node Express and MongoDB",
    description: "I completed my Basics of web course from Codedamn.",
    date: "Dec, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "udemy.png",
    logo: "udemy_logo.png",
    image: "nodejs.png",
  },
  {
    id: "6",
    title: "Django",
    description:
      "I completed my Basics of web course from Youtube codevolution channel.",
    date: "Dec, 2022",
    certificate: "https://codedamn.com/certificates/1b1b1f9e1b5d",
    icon: "udemy.png",
    logo: "udemy_logo.png",
    image: "react.png",
  },
];
