import { CertificationType } from "@/@types";
import { GITHUB_URL } from ".";

export const CERIFICATIONS: CertificationType[] = [
  {
    id: "1",
    title: "Data Structures and Algorithms",
    description: "Earned ELITE + SILVER for scoring 78% in Data Structures and Algorithms using Python from NPTEL",
    certificate: "https://www.hackerrank.com/certificates/9b1b1f9e1b5d",
    date: "09 Sept, 2022",
    icon: "",
    logo: "",
    image: "second_rank.png",
  },
  {
    id: "2",
    title: "Postman Student Expert",
    description: "Awarded for demonstrating proficiency with APIs and Postman by completing foundational tasks in Postman.",
    date: "17 Aug, 2023",
    certificate: "https://badgr.com/public/assertions/mX9cDBSTSjiEYaLBkpAzPw?identity__email=darsigangothri@gmail.com",
    icon: "",
    logo: "",
    image: "postman.png",
  },
  {
    id: "3",
    title: "Problem Solving (Basic)",
    description: "Successfully cleared the assesment for the skill Problem solving (Basic)",
    date: "20 Jan, 2022",
    certificate: "https://www.hackerrank.com/certificates/8f23c7a17cef",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "first_rank.png",
  },
  {
    id: "4",
    title: "Problem Solving (Intermediate)",
    description: "Successfully cleared the assesment for the skill Problem solving (Intermediate)",
    date: "25 Jan, 2022",
    certificate: "https://www.hackerrank.com/certificates/8ffb9bb9d1f0",
    icon: "hr.png",
    logo: "hr_logo.png",
    image: "first_rank.png",
  },
  {
    id: "5",
    title: "Node Express and MongoDB",
    description: "Completed Node, Express and MongoDB course from Udemy",
    date: "19 Mar, 2023",
    certificate: "https://drive.google.com/file/d/1-fnPpqkMjVYuRqaZxrtUJydCeLrJjlRg/view",
    icon: "udemy.png",
    logo: "udemy_logo.png",
    image: "nodejs.png",
  },
  {
    id: "6",
    title: "Django",
    description:
      "Completed Full Stack in Python with Django course from Udemy",
    date: "15 May, 2022",
    certificate: "https://drive.google.com/file/d/1J4pq_Cl-8cpV0mEUTAXXIXwbRZKFNtRL/view",
    icon: "udemy.png",
    logo: "udemy_logo.png",
    image: "django.svg",
  },
];
